function [features, featureNames, roiAbsoluteCentroid ] = readNormCutFeatures( dataFile )
%unpack previously calculated normalized cut features and put them into
%design matrix format
normCutFeatures = dataFile.normCutFeatures

totalProjNormedIntesnity = cell2mat(normCutFeatures(:,1));
totalProjUnnormedIntesnity =  cell2mat(normCutFeatures(:,2));
avgProjNormedIntensity =  cell2mat(normCutFeatures(:,3));
avgProjUnnormedIntensity   =  cell2mat(normCutFeatures(:,4));
roiMeanIntensitySpectrum   =  cell2mat(normCutFeatures(:,5));
roiMeanIntensityMagnitude = cell2mat(normCutFeatures(:,6));
corrMatROI = normCutFeatures(:,7);
corrMatGlob = normCutFeatures(:,8);
roiTotalPixels = cell2mat(normCutFeatures(:,9));
roiCentroidOffset = cell2mat(normCutFeatures(:,10));
roiAbsoluteCentroid = cell2mat(normCutFeatures(:,11));

unpackCorrMat = @(input) cellfun(@(datum) [datum(1,2:6) datum(2,3:6) datum(3,4:6) datum(4,5:6) datum(5,6)]  ,input, 'UniformOutput', false);

features = [totalProjNormedIntesnity  totalProjUnnormedIntesnity avgProjNormedIntensity...
    avgProjUnnormedIntensity  roiMeanIntensitySpectrum  roiMeanIntensityMagnitude...
    cell2mat(unpackCorrMat(corrMatROI))  cell2mat(unpackCorrMat(corrMatGlob))...
    roiTotalPixels  roiCentroidOffset];

featureNames = {'Normalized projected intenisty sum','Unnormalized projected intenisty sum',...
    'Normalized projected intenisty avg','Unnormalized projected intenisty avg',...
    'NCROI Intensity Mean Channel 1', 'NCROI Intensity Mean Channel 2', 'NCROI Intensity Mean Channel 3',...
    'NCROI Intensity Mean Channel 4', 'NCROI Intensity Mean Channel 5', 'NCROI Intensity Mean Channel 6',...
    'NCROI Intensity Mean Magnitude', 'NCROI CorrMat 12',  'NCROI CorrMat 13','NCROI CorrMat 14',...
    'NCROI CorrMat 15', 'NCROI CorrMat 16', 'NCROI CorrMat 23','NCROI CorrMat 24','NCROI CorrMat 25',...
    'NCROI CorrMat 26', 'NCROI CorrMat 34', 'NCROI CorrMat 35', 'NCROI CorrMat 36', 'NCROI CorrMat 45',...
    'NCROI CorrMat 46', 'NCROI CorrMat 56', 'Global CorrMat 12',  'Global CorrMat 13','Global CorrMat 14',...
    'Global CorrMat 15', 'Global CorrMat 16', 'Global CorrMat 23','Global CorrMat 24','Global CorrMat 25',...
    'Global CorrMat 26', 'Global CorrMat 34', 'Global CorrMat 35', 'Global CorrMat 36', 'Global CorrMat 45',...
    'Global CorrMat 46', 'Global CorrMat 56', 'NCROI Num pixels', 'NCROI Centroid Offset X',...
    'NCROI Centroid Offset Y', 'NCROI Centroid Offset Z'};

end

